<?php

use Yii;
/**
 * Created by PhpStorm.
 * User: tsingsun
 * Date: 2016/11/14
 * Time: 下午4:25
 */
class DefaultControllerTest extends \yiiunit\extensions\graphql\TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->mockWebApplication();
    }

    public function testActionIndex(){
        $_GET = [
            'query'=> $this->queries['hello'],
        ];
        $dc = new \yii\graphql\controllers\DefaultController('default',Yii::$app->getModule('graphql'));
        $result = $dc->ActionIndex();
        $this->assertArrayHasKey('data',$result);
    }
}
