<?php
/**
 * Created by PhpStorm.
 * User: tsingsun
 * Date: 2016/11/29
 * Time: 下午3:05
 */

namespace yiiunit\extensions\graphql;


class GraphqlMutationTest extends TestCase
{
    /**
     * @var \yii\graphql\GraphQL GraphQL
     */
    protected $graphQL;


    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->mockWebApplication();
        $this->graphQL = \Yii::$app->getModule('graphql')->getGraphQL();
    }

    public function testUpdateUserPwd(){
        $query = "mutation updateUserPwd{
            updateUserPwd(id: \"qsli@google.com\", password: \"123456\") {
                id,
                firstName
            }
        }";
        $expect = [
            'updateUserPwd' => ['id' => "1", 'firstName' => "John"]
        ];
        $result = $this->graphQL->query($query, null, \Yii::$app);
        $this->assertArrayHasKey('data', $result);
        $this->assertEquals($expect, $result['data']);
    }

    public function testValidator()
    {
        $query = "
            mutation updateUserPwd{
                updateUserPwd(id: \"1001\",password: \"123456\") {
                    id,
                    email
                }
            }
        ";
        $result = $this->graphQL->query($query, null, \Yii::$app);
        $this->assertArrayHasKey('errors', $result);
    }
}
