<?php
/**
 * Created by PhpStorm.
 * User: tsingsun
 * Date: 2016/11/29
 * Time: 下午3:05
 */

namespace yiiunit\extensions\graphql;


class GraphqlMutationTest extends TestCase
{
    /**
     * @var \yii\graphql\GraphQL GraphQL
     */
    protected $graphQL;


    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->mockWebApplication();
        $this->graphQL = \Yii::$app->getModule('graphql')->getGraphQL();
    }

    public function testUpdateUserPwd(){
        $result = $this->graphQL->queryAndReturnResult($this->queries['updateObject'],null,\Yii::$app);
        $this->assertObjectHasAttribute('data', $result);
        $this->assertCount(0, $result->errors);
    }
}
