<?php
/**
 * Created by PhpStorm.
 * User: tsingsun
 * Date: 2016/11/29
 * Time: 下午3:05
 */

namespace yiiunit\extensions\graphql;


class GraphqlMutationTest extends TestCase
{
    /**
     * @var \yii\graphql\GraphQL GraphQL
     */
    protected $graphQL;


    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->mockWebApplication();
        $this->graphQL = \Yii::$app->getModule('graphql')->getGraphQL();
    }

    public function testUpdateUserPwd(){
        $result = $this->graphQL->query($this->queries['updateObject'], null, \Yii::$app);
        $this->assertArrayHasKey('data', $result);
        $this->assertArrayNotHasKey('errors', $result);
    }

    public function testValidator()
    {
        $result = $this->graphQL->query($this->queries['mutationValidate'], null, \Yii::$app);
        $this->assertArrayHasKey('errors', $result);
    }
}
